<?php

/**
 * @file
 * The contest_webform module file.
 */

/**
 * Custom validation function for the contest setting form.
 */
function contest_webform_entry_form_submit($form, &$state) {
  $form_state = ContestWebformHelper::getValues('submit', $state);

  return contest_entry_form_submit($form, $form_state);
}

/**
 * Custom submit function for the contest entry form.
 */
function contest_webform_entry_form_validate($form, &$state) {
  $form_state = ContestWebformHelper::getValues('validate', $state);

  return contest_entry_form_validate($form, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function contest_webform_form_alter(&$form, &$state, $form_id) {
  $access = TRUE;

  if (!preg_match('/^webform_client_form_(\d+)$/', $form_id, $m) || !ContestWebformStorage::webformExists($m[1])) {
    return;
  }
  drupal_alter('contest_entry_access', $access);

  if (!$access) {
    return;
  }
  $contest_id = ContestWebformHelper::getContestId($form);

  if (!$contest_id || !ContestStorage::running($contest_id)) {
    return;
  }
  $entry_form = contest_entry_form();

  unset($entry_form['submit']);
  unset($entry_form['#id']);
  unset($entry_form['#submit']);
  unset($entry_form['#validate']);

  $entry_form['fieldset']['contest_id'] = array(
    '#type'  => 'value',
    '#value' => $contest_id,
  );
  if (module_exists('contest_tnc')) {
    $tnc = ContestTncHelper::getTnc(node_load($contest_id));

    $entry_form['contest_tnc'] = array(
      '#type'   => 'markup',
      '#markup' => drupal_render($tnc),
    );
  }
  $form['submitted'] += $entry_form;

  $form['#submit'][] = 'contest_webform_entry_form_submit';
  $form['#validate'][] = 'contest_webform_entry_form_validate';
}

/**
 * Implements hook_help().
 */
function contest_webform_help($path, $arg) {
  switch ($path) {
    case 'admin/help#contest_webform':
      $txt = file_get_contents(drupal_get_path('module', 'contest_webform') . '/README.txt');
      return str_replace("\n", "\n<br />", check_plain($txt));
  }
}

/**
 * Implements hook_webform_webform_component_info().
 */
function contest_webform_webform_component_info() {
  return array(
    'contest'       => array(
      'label'       => t('Contest'),
      'description' => t('Contest webform element.'),
      'file'        => 'contest_webform.component.inc',
      'features'    => array(
        'conditional_action_set' => TRUE,
        'css_classes'            => FALSE,
        'description'            => FALSE,
        'email_address'          => TRUE,
        'email_name'             => TRUE,
        'private'                => FALSE,
        'required'               => FALSE,
        'title_display'          => FALSE,
        'wrapper_classes'        => FALSE,
      ),
    ),
  );
}
